export const craftEquipmentsData = [
  {
    id: "cw_goblin",
    name: "ファングナックル",
    type: "weapon",
    attack: 12,
    defense: null,
    rarity: 1,
    description: "ゴブリンの牙を刃に仕込んだ拳具。粗削りだが威力は十分。",
    craftCost: 140,
  },
  {
    id: "cw_beetle",
    name: "ソーラーチタニア",
    type: "weapon",
    attack: 18,
    defense: null,
    rarity: 2,
    description: "サンビートルの甲殻を鍛造した光沢の剣。陽光で輝く。",
    craftCost: 260,
  },
  {
    id: "cw_wolf",
    name: "ハウリングエッジ",
    type: "weapon",
    attack: 24,
    defense: null,
    rarity: 3,
    description: "フィールドウルフの毛皮を巻いた剣柄。斬撃に風圧が宿る。",
    craftCost: 420,
  },
  {
    id: "cw_crystal",
    name: "クレストシア",
    type: "weapon",
    attack: 34,
    defense: null,
    rarity: 4,
    description: "クリスタルスライムの欠片から生まれた純粋結晶刃。魔力伝導率が高い。",
    craftCost: 700,
  },
  {
    id: "cw_magma",
    name: "マグマコアランス",
    type: "weapon",
    attack: 46,
    defense: null,
    rarity: 4,
    description: "マグマの核石を槍穂に埋め込んだ灼熱のランス。触れるだけで焼ける。",
    craftCost: 1150,
  },
  {
    id: "cw_specter",
    name: "スペクトラルロッド",
    type: "weapon",
    attack: 42,
    defense: null,
    rarity: 4,
    description: "スペクターの霊布を纏う杖。霊気が漂い、魔法威力を高める。",
    craftCost: 980,
  },
  {
    id: "cw_dragon",
    name: "逆鱗断ち",
    type: "weapon",
    attack: 64,
    defense: null,
    rarity: 5,
    description: "ドラゴンの逆鱗を砥石代わりに鍛え上げた剣。竜種に致命的な一撃を与える。",
    craftCost: 2600,
  },

  // 🛡 防具系
  {
    id: "ca_wolf",
    name: "ウルフェンコート",
    type: "armor",
    attack: null,
    defense: 9,
    rarity: 2,
    description: "フィールドウルフの毛皮で仕立てた防具。軽く暖かく動きやすい。",
    craftCost: 280,
  },
  {
    id: "ca_lizard",
    name: "スケイルガード",
    type: "armor",
    attack: null,
    defense: 17,
    rarity: 3,
    description: "洞窟トカゲの鱗を繋ぎ合わせた防具。衝撃吸収に優れる。",
    craftCost: 620,
  },
  {
    id: "ca_rune",
    name: "ルーンシェル",
    type: "armor",
    attack: null,
    defense: 26,
    rarity: 4,
    description: "ルーン鋼片を織り込んだ鎧。魔法攻撃を部分的に反射する。",
    craftCost: 1180,
  },
  {
    id: "ca_dimension",
    name: "ディメンションメイル",
    type: "armor",
    attack: null,
    defense: 34,
    rarity: 5,
    description: "次元のかけらを装甲化した鎧。空間を歪め、被弾を遅延させる。",
    craftCost: 2100,
  },
] as const;
