import { ShopItem } from "@/types/shopItems";

export const SHOP_ITEMS: ShopItem[] = [
  // 🗡 武器
  { id: "w1", name: "木の棒", type: "weapon", price: 60, attack: 4, description: "枝のような武器。最初の戦いに使われる。" },
  { id: "w2", name: "ブロンズソード", type: "weapon", price: 120, attack: 7, description: "青銅で作られた安価な剣。" },
  { id: "w3", name: "アイアンソード", type: "weapon", price: 200, attack: 10, description: "一般兵士が使う鉄の剣。" },
  { id: "w4", name: "スチールブレード", type: "weapon", price: 300, attack: 13, description: "鍛えられた鋼の剣。安定した性能を誇る。" },
  { id: "w5", name: "ミスリルソード", type: "weapon", price: 420, attack: 16, description: "軽く、魔力伝導性の高い剣。" },
  { id: "w6", name: "アイスブランド", type: "weapon", price: 560, attack: 19, description: "冷気を帯びた剣。炎に弱い敵に効果的。" },
  { id: "w7", name: "フレイムタン", type: "weapon", price: 720, attack: 22, description: "炎の魔力を宿す灼熱の剣。" },
  { id: "w8", name: "サンダーブレード", type: "weapon", price: 900, attack: 25, description: "雷属性を帯びた刃。機械系に強い。" },
  { id: "w9", name: "ダークソード", type: "weapon", price: 1100, attack: 29, description: "闇の呪いを宿した剣。使い手を蝕む力を持つ。" },
  { id: "w10", name: "ホーリーランス", type: "weapon", price: 1320, attack: 33, description: "聖なる力を宿した槍。アンデッドに強い。" },
  { id: "w11", name: "ドラゴンキラー", type: "weapon", price: 1560, attack: 37, description: "竜種に特効を持つ重厚な剣。" },
  { id: "w12", name: "ルーンブレード", type: "weapon", price: 1820, attack: 41, description: "魔法力を吸収し攻撃に転換する剣。" },
  { id: "w13", name: "クリスタルソード", type: "weapon", price: 2100, attack: 45, description: "透明な輝きを放つ神秘の剣。" },
  { id: "w14", name: "マサムネ", type: "weapon", price: 2420, attack: 49, description: "東方の伝説に名を残す名刀。切れ味抜群。" },
  { id: "w15", name: "村雨", type: "weapon", price: 2780, attack: 53, description: "濡れたように光る妖刀。魔を斬る力を持つ。" },
  { id: "w16", name: "バスタードソード", type: "weapon", price: 3180, attack: 57, description: "力と技を兼ね備えた万能の大剣。" },
  { id: "w17", name: "ラグナロク", type: "weapon", price: 3640, attack: 62, description: "神々の最終戦争で使われた伝説の剣。" },
  { id: "w18", name: "アルテマウェポン", type: "weapon", price: 4160, attack: 67, description: "戦士の魂に呼応して強さを増す究極の武器。" },
  { id: "w19", name: "オメガソード", type: "weapon", price: 4740, attack: 72, description: "古代文明の技術で作られた機械仕掛けの剣。" },
  { id: "w20", name: "ゼニスブレード", type: "weapon", price: 5400, attack: 78, description: "創世の光を放つ、全てを超越した剣。" },

  // 🛡 防具
  { id: "a1", name: "布の服", type: "armor", price: 80, defense: 2, description: "ただの布の服。最低限の防御力。" },
  { id: "a2", name: "革の鎧", type: "armor", price: 150, defense: 4, description: "動きやすい革製の鎧。" },
  { id: "a3", name: "チェインメイル", type: "armor", price: 240, defense: 6, description: "金属の輪をつなげた軽量鎧。" },
  { id: "a4", name: "アイアンアーマー", type: "armor", price: 360, defense: 8, description: "鉄製の鎧。物理攻撃に強い。" },
  { id: "a5", name: "ミスリルメイル", type: "armor", price: 500, defense: 10, description: "軽く魔法防御にも優れる鎧。" },
  { id: "a6", name: "フレイムアーマー", type: "armor", price: 660, defense: 12, description: "炎耐性を持つ鎧。" },
  { id: "a7", name: "アイスアーマー", type: "armor", price: 840, defense: 14, description: "冷気を防ぐ鎧。炎には弱い。" },
  { id: "a8", name: "サンダーメイル", type: "armor", price: 1040, defense: 16, description: "雷耐性を持つ鎧。" },
  { id: "a9", name: "ドラゴンメイル", type: "armor", price: 1260, defense: 18, description: "竜の鱗で作られた頑丈な鎧。" },
  { id: "a10", name: "クリスタルアーマー", type: "armor", price: 1500, defense: 20, description: "神秘的な輝きを放つ鎧。" },
  { id: "a11", name: "ダークアーマー", type: "armor", price: 1760, defense: 22, description: "闇属性を帯びた鎧。聖に弱い。" },
  { id: "a12", name: "ホーリーメイル", type: "armor", price: 2040, defense: 24, description: "聖なる力が宿る鎧。" },
  { id: "a13", name: "アダマンアーマー", type: "armor", price: 2340, defense: 26, description: "伝説の金属アダマンタイト製。" },
  { id: "a14", name: "リフレクトアーマー", type: "armor", price: 2680, defense: 28, description: "一部の魔法を反射する特殊な鎧。" },
  { id: "a15", name: "ミラージュアーマー", type: "armor", price: 3060, defense: 30, description: "幻影を生み出し回避率が上がる。" },
  { id: "a16", name: "クリムゾンメイル", type: "armor", price: 3480, defense: 32, description: "赤い輝きを放つ魔法防御重視の鎧。" },
  { id: "a17", name: "セイントローブ", type: "armor", price: 3960, defense: 34, description: "僧侶専用の聖属性ローブ。" },
  { id: "a18", name: "オメガスーツ", type: "armor", price: 4500, defense: 36, description: "全属性耐性を持つ究極の装備。" },
  { id: "a19", name: "神の鎧", type: "armor", price: 5100, defense: 38, description: "神々の加護を受けた伝説の鎧。" },
  { id: "a20", name: "光の鎧", type: "armor", price: 5800, defense: 40, description: "光そのものが形を成した究極防具。" },

  // 💍 アクセサリー
  { id: "ac1", name: "力の指輪", type: "accessory", price: 300, effect: "攻撃力+5", description: "力がみなぎる指輪。" },
  { id: "ac2", name: "守りの腕輪", type: "accessory", price: 400, effect: "防御力+5", description: "身を守る加護を持つ腕輪。" },
  { id: "ac3", name: "魔力のイヤリング", type: "accessory", price: 600, effect: "魔力+10", description: "魔法の威力を高める耳飾り。" },
  { id: "ac4", name: "スピードブーツ", type: "accessory", price: 800, effect: "素早さ+10%", description: "動きを軽くする靴。" },
  { id: "ac5", name: "知恵の眼鏡", type: "accessory", price: 1000, effect: "経験値+20%", description: "学習効率が上がる眼鏡。" },
  { id: "ac6", name: "リジェネリング", type: "accessory", price: 1200, effect: "毎ターンHP回復", description: "生命力を高める指輪。" },
  { id: "ac7", name: "毒消しのペンダント", type: "accessory", price: 1300, effect: "毒無効", description: "毒の影響を防ぐお守り。" },
  { id: "ac8", name: "スリープピアス", type: "accessory", price: 1400, effect: "睡眠無効", description: "悪夢から身を守る耳飾り。" },
  { id: "ac9", name: "マジックリング", type: "accessory", price: 1600, effect: "MP回復速度上昇", description: "魔力の流れを安定させる指輪。" },
  { id: "ac10", name: "エルメスの靴", type: "accessory", price: 1800, effect: "常にヘイスト", description: "俊敏の神の名を冠した靴。" },
  { id: "ac11", name: "リボン", type: "accessory", price: 2000, effect: "全状態異常無効", description: "すべての呪いを防ぐ奇跡のリボン。" },
  { id: "ac12", name: "幸運のお守り", type: "accessory", price: 2200, effect: "ドロップ率+20%", description: "運を引き寄せる護符。" },
  { id: "ac13", name: "バリアリング", type: "accessory", price: 2500, effect: "ダメージ-10%", description: "見えない壁を展開する指輪。" },
  { id: "ac14", name: "マナクリスタル", type: "accessory", price: 2800, effect: "MP+50", description: "魔力を蓄える水晶。" },
  { id: "ac15", name: "アビスチャーム", type: "accessory", price: 3200, effect: "闇属性攻撃強化", description: "深淵の力を宿すお守り。" },
  { id: "ac16", name: "ホーリーチャーム", type: "accessory", price: 3500, effect: "聖属性強化", description: "光の加護を受けたお守り。" },
  { id: "ac17", name: "オメガチャーム", type: "accessory", price: 4000, effect: "全能力+10%", description: "古代兵器の力を宿す禁断の装飾品。" },
  { id: "ac18", name: "フェニックスの羽根飾り", type: "accessory", price: 4500, effect: "戦闘不能時1回自動復活", description: "不死鳥の力を宿す髪飾り。" },
  { id: "ac19", name: "賢者の石", type: "accessory", price: 5000, effect: "全能力+50%", description: "全ての能力を高める伝説の石。" },
  { id: "ac20", name: "ゼロスフィア", type: "accessory", price: 8000, effect: "全能力+100%＆HP自動回復", description: "この世の理を超えた究極の装飾品。" },
];
